name: supports_color
version: 0.1.1
author: Sean Eagan <seaneagan1@gmail.com>
description: Detect whether the current terminal supports color.  This is a dart port of the https://www.npmjs.org/package/supports-color.
homepage: https://github.com/seaneagan/supports_color

environment:
  sdk: '>=2.0.0-dev.54.0 <3.0.0' # Defined by test package below.

dev_dependencies:
  test: '^1.3.0'
